### ISSUE TITLE
ERROR: Crypto module missing, however it is installed

### ISSUE THREAD

**Issue by dfirhoze** [markmckinnon/cLeapp#40]
Running on a Mac with Python 3.10.0. Any quick fix suggestions?

user@AdminisatorsMBP cLeapp % python3 cleapp.py --help
Traceback (most recent call last):
  File "/Users/user/Desktop/DFIR TOOLS/cLeapp/cleapp.py", line 10, in <module>
    from scripts.cleap_artifacts import *
  File "/Users/user/Desktop/DFIR TOOLS/cLeapp/scripts/cleap_artifacts.py", line 18, in <module>
    from scripts.artifacts.chromeLoginData import get_chromeLoginData
  File "/Users/user/Desktop/DFIR TOOLS/cLeapp/scripts/artifacts/chromeLoginData.py", line 6, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by markmckinnon** [comment]
Can you try it with python 3.9. There have been some issues with python 3.10. Will have to test with python 3.10 to see if there are any issues.
